<template>
  <div class="setting-panel-gui">
    <g-field-collapse
        label="雷达"
    >
      <g-field
          label="样式"
          :level="2"
      >
        <n-checkbox v-model:checked="config.radar.splitArea.show">背景</n-checkbox>
        <n-checkbox v-model:checked="config.radar.splitLine.show">分割线</n-checkbox>
      </g-field>
      <g-field
          :level="2"
          label="雷达形状"
      >
        <n-select
            v-model:value="config.radar.shape"
            size="small"
            :options="RadarShapeEnumList"
            placeholder="选择形状"
        />
      </g-field>
      <g-field
          :level="2"
          label="坐标轴"
      >
        <n-checkbox v-model:checked="config.radar.axisLine.show">轴线</n-checkbox>
        <n-checkbox v-model:checked="config.radar.axisTick.show">刻度</n-checkbox>
      </g-field>
      <g-field
          :level="2"
          label="范围"
      >
        <g-input-number
            v-model="radarProp.radius[0]"
            :min="0"
            :step="1"
            @update:modelValue="updateRadius0"
            suffix="%"
            label="最小值"
        />
        <g-input-number
            v-model="radarProp.radius[1]"
            :min="0"
            :max="100"
            :step="1"
            @update:modelValue="updateRadius1"
            suffix="%"
            label="最大值"
        />
      </g-field>
      <g-field
          :level="2"
          label="偏移"
      >
        <g-input-number
            v-model="radarProp.center[0]"
            :min="0"
            :step="1"
            @update:modelValue="updateCenter0"
            suffix="%"
            label="最小值"
        />
        <g-input-number
            v-model="radarProp.center[1]"
            :min="0"
            :max="100"
            :step="1"
            @update:modelValue="updateCenter1"
            suffix="%"
            label="最大值"
        />
      </g-field>
      <g-field
          :level="2"
          label="颜色"
      >
        <g-color-picker
            v-model="config.radar.axisName.color"
        />
      </g-field>
      <g-field
          :level="2"
          label="大小"
      >
        <g-input-number
            v-model="config.radar.axisName.fontSize"
            :min="0"
            :max="100"
            :step="1"
        />
      </g-field>
      <g-field
          :level="2"
          label="背景透明度"
      >
        <g-input-number
            v-model="config.series[0].areaStyle.opacity"
            :min="0"
            :max="1"
            :step="0.1"
        />
      </g-field>
    </g-field-collapse>

    <g-field-collapse
        v-model="config.tooltip.show"
        :toggle="true"
        label="提示框"
    >
      <g-field-collapse
          label="文本样式"
      >
        <g-field
            :level="2"
            label="字号"
        >
          <g-input-number
              v-model="config.tooltip.textStyle.fontSize"
              :min="12"
              :max="100"
              :step="1"
              suffix="px"
          />
        </g-field>
        <g-field
            :level="2"
            label="颜色"
        >
          <g-color-picker
              v-model="config.tooltip.textStyle.color"
          />
        </g-field>
        <g-field
            :level="2"
            label="字体粗细"
        >
          <g-select
              v-model="config.tooltip.textStyle.fontWeight"
              :data="fontWeights"
          />
        </g-field>
      </g-field-collapse>
      <g-field-collapse
          label="弹框背景"
      >
        <g-field
            :level="2"
            label="背景边距"
            :is-flat="true"
        >
          <g-input-number
              v-model="config.tooltip.background.padding.h"
              :min="0"
              :max="100"
              :step="1"
              suffix="px"
              inline="inline"
              label="水平"
          />
          <g-input-number
              v-model="config.tooltip.background.padding.v"
              :min="0"
              :max="100"
              :step="1"
              suffix="px"
              inline="inline"
              label="垂直"
          />
        </g-field>
        <g-field
            :level="2"
            label="背景色"
        >
          <g-color-picker
              v-model="config.tooltip.background.color"
          />
        </g-field>
      </g-field-collapse>
      <g-field-collapse
          v-model="config.tooltip.pointer.show"
          :toggle="true"
          label="轴指示器"
      >
        <g-field
            :level="2"
            label="线型样式"
            :is-flat="true"
        >
          <g-select
              v-model="config.tooltip.pointer.line.type"
              :data="lineStyles"
              inline="inline"
              label="类型"
          />
          <g-input-number
              v-model="config.tooltip.pointer.line.width"
              :min="0"
              :max="100"
              :step="1"
              suffix="px"
              inline="inline"
              label="粗细"
          />
          <g-color-picker
              v-model="config.tooltip.pointer.line.color"
              inline="inline-single"
              label="颜色"
          />
          <g-input-number
              v-if="config.tooltip.pointer.line.type === 'dashed'"
              v-model="config.tooltip.pointer.line.dashedLength"
              :min="0"
              :max="100"
              :step="1"
              suffix="px"
              inline="inline"
              label="长度"
          />
          <g-input-number
              v-if="config.tooltip.pointer.line.type === 'dashed'"
              v-model="config.tooltip.pointer.line.dashedSpace"
              :min="0"
              :max="100"
              :step="1"
              suffix="px"
              inline="inline"
              label="间距"
          />
        </g-field>
      </g-field-collapse>
    </g-field-collapse>
    <g-field-collapse
        v-model="config.legend.show"
        :toggle="true"
        label="图例"
    >
      <g-field
          :level="2"
          label="位置"
      >
        <g-select
            v-model="config.legend.position"
            :data="legendLocations"
        />
      </g-field>
      <g-field
          :level="2"
          label="布局方式"
      >
        <n-radio-group
            v-model:value="config.legend.orient"
            size="small"
        >
          <n-radio-button
              v-for="em in orients"
              :key="em.id"
              :value="em.id"
          >
            {{ em.value }}
          </n-radio-button>
        </n-radio-group>
      </g-field>
      <g-field
          :level="2"
          label="文本样式"
          :is-flat="true"
      >
        <g-input-number
            v-model="config.legend.textStyle.fontSize"
            :min="0"
            :max="100"
            :step="1"
            suffix="px"
            inline="inline"
            label="字号"
        />
        <g-color-picker
            v-model="config.legend.textStyle.color"
            inline="inline"
            label="颜色"
        />
        <g-select
            v-model="config.legend.textStyle.fontWeight"
            :data="fontWeights"
            inline="inline-single"
            label="字体粗细"
        />
      </g-field>
      <g-field-collapse
          v-model="config.legend.symbol.show"
          :toggle="true"
          label="图例图标"
      >
        <g-field
            :level="2"
            label="图标"
        >
          <g-select-shape
              v-model="config.legend.symbol.icon"
              :shapes="echartIcons"
          />
        </g-field>
        <g-field
            :level="2"
            label="宽度"
        >
          <g-input-number
              v-model="config.legend.symbol.width"
              :min="0"
              :max="100"
              :step="1"
              suffix="px"
          />
        </g-field>
        <g-field
            :level="2"
            label="高度"
        >
          <g-input-number
              v-model="config.legend.symbol.height"
              :min="0"
              :max="100"
              :step="1"
              suffix="px"
          />
        </g-field>
        <g-field
            :level="2"
            label="间隔"
        >
          <g-input-number
              v-model="config.legend.symbol.gap"
              :min="-1000"
              :max="1000"
              :step="1"
              suffix="px"
          />
        </g-field>
      </g-field-collapse>
      <g-field-collapse
          v-model="config.legend.page.enabled"
          :toggle="true"
          label="翻页功能"
      >
        <g-field
            :level="2"
            label="容器尺寸"
            :is-flat="true"
        >
          <g-input-number
              v-model="config.legend.page.size.width"
              :min="0"
              :max="1000"
              :step="1"
              suffix="px"
              inline="inline"
              label="宽度"
          />
          <g-input-number
              v-model="config.legend.page.size.height"
              :min="0"
              :max="1000"
              :step="1"
              suffix="px"
              inline="inline"
              label="高度"
          />
        </g-field>
        <g-field
            :level="2"
            label="翻页按钮"
            :is-flat="true"
        >
          <g-input-number
              v-model="config.legend.page.button.size"
              :min="0"
              :max="100"
              :step="1"
              suffix="px"
              inline="inline"
              label="尺寸"
          />
          <g-color-picker
              v-model="config.legend.page.button.color"
              inline="inline"
              label="颜色"
          />
          <g-color-picker
              v-model="config.legend.page.button.inactiveColor"
              inline="inline-single"
              label="禁用颜色"
          />
        </g-field>
        <g-field
            :level="2"
            label="页码颜色"
        >
          <g-color-picker
              v-model="config.legend.page.pageNumColor"
          />
        </g-field>
      </g-field-collapse>
    </g-field-collapse>
    <g-field-collapse
        v-model="config.animation.enabled"
        :toggle="true"
        label="动画"
    >
      <g-field
          :level="2"
          label="持续时间"
      >
        <g-input-number
            v-model="config.animation.duration"
            :min="0"
            :step="100"
            suffix="ms"
        />
      </g-field>
      <g-field
          :level="2"
          label="缓动效果"
      >
        <g-select
            v-model="config.animation.easing"
            :data="animationEasings"
        />
      </g-field>
      <g-field
          :level="2"
          label="延迟"
      >
        <g-input-number
            v-model="config.animation.delay"
            :min="0"
            :step="100"
            suffix="ms"
        />
      </g-field>
    </g-field-collapse>
  </div>
</template>
<script lang='ts'>
import { defineComponent, PropType, toRef, reactive, computed } from 'vue'
import Cadar, {RadarShapeEnumList} from './cadar'

export default defineComponent({
  name: 'VCadarProp',
  props: {
    com: {
      type: Object as PropType<Cadar>,
      required: true,
    },
  },
  setup(props) {
    const config = toRef(props.com, 'config')

    const radarProp = reactive({
      radius: [0, 60],
      center: [50, 55]
    })

    // 更新处理
    const updateRadius0 = (value: number) => {
      config.value.radar.radius[0] = `${value}%`
    }

    const updateRadius1 = (value: number) => {
      config.value.radar.radius[1] = `${value}%`
    }

    // 更新处理
    const updateCenter0 = (value: number) => {
      config.value.radar.center[0] = `${value}%`
    }

    const updateCenter1 = (value: number) => {
      config.value.radar.center[1] = `${value}%`
    }

    // 百分比格式化 percent
    const sliderFormatTooltip = (v: number) => {
      return `${v}%`
    }

    return{
      config,
      radarProp,
      updateRadius0,
      updateRadius1,
      updateCenter0,
      updateCenter1,
      sliderFormatTooltip,
      RadarShapeEnumList,
    }
  }
})
</script>