<template>
  <div class="setting-panel-gui">
    <g-field-collapse
        label="仪表盘"
    >
      <g-field
          :level="2"
          label="位置"
      >
        <g-input-number
            v-model="config.seriesData.center[0]"
            :min="1"
            :max="100"
            :step="1"
        />
        <g-input-number
            v-model="config.seriesData.center[1]"
            :min="1"
            :max="100"
            :step="1"
        />
      </g-field>
      <g-field
          :level="2"
          label="开始角度"
      >
        <g-input-number
            v-model="config.seriesData.startAngle"
            :min="1"
            :max="180"
            :step="1"
        />
      </g-field>
      <g-field
          :level="2"
          label="开始角度"
      >
        <g-input-number
            v-model="config.seriesData.endAngle"
            :min="-180"
            :max="100"
            :step="1"
        />
      </g-field>
      <g-field
          :level="2"
          label="最大值"
      >
        <g-input-number
            v-model="config.seriesData.max"
            :min="0"
            :max="100"
            :step="1"
        />
      </g-field>
      <g-field
          :level="2"
          label="最小值"
      >
        <g-input-number
            v-model="config.seriesData.min"
            :min="0"
            :max="100"
            :step="1"
        />
      </g-field>
      <g-field
          :level="2"
          label="分割值"
      >
        <g-input-number
            v-model="config.seriesData.splitNumber"
            :min="0"
            :max="100"
            :step="1"
        />
      </g-field>
      <g-field
          :level="2"
          label="填充类型"
      >
        <n-radio-group
            v-model:value="config.seriesData.itemStyle.color.type"
            size="small"
        >

          <n-radio-button
              v-for="em in fillTypes"
              :key="em.id"
              :value="em.id"
          >
            {{ em.value }}
          </n-radio-button>
        </n-radio-group>
      </g-field>
      <g-field
          v-if="config.seriesData.itemStyle.color.type === 'solid'"
          :level="2"
          label="颜色"
      >
        <g-color-picker
            v-model="config.seriesData.itemStyle.color.value"
        />
      </g-field>
      <g-field
          v-if="config.seriesData.itemStyle.color.type === 'gradient'"
          :level="2"
          label="开始颜色"
      >
        <g-color-picker
            v-model="config.seriesData.itemStyle.color.from"
        />
      </g-field>
      <g-field
          v-if="config.seriesData.itemStyle.color.type === 'gradient'"
          :level="2"
          label="结束颜色"
      >
        <g-color-picker
            v-model="config.seriesData.itemStyle.color.to"
        />
      </g-field>
      <g-field
          :level="2"
          label="填充宽度"
      >
        <g-input-number
            v-model="config.seriesData.progress.width"
            :min="1"
            :max="100"
            :step="1"
        />
      </g-field>
    </g-field-collapse>
    <g-field-collapse
        v-model="config.seriesData.axisLine.show"
        :toggle="true"
        label="仪表盘轴线"
    >
      <g-field
          :level="2"
          label="填充宽度"
      >
        <g-input-number
            v-model="config.seriesData.axisLine.lineStyle.width"
            :min="1"
            :max="100"
            :step="1"
        />
      </g-field>
    </g-field-collapse>
    <g-field-collapse
        v-model="config.seriesData.axisTick.show"
        :toggle="true"
        label="仪表盘刻度"
    >
      <g-field
          :level="2"
          label="刻度线与轴线的距离"
      >
        <g-input-number
            v-model="config.seriesData.axisTick.distance"
            :min="-100"
            :max="100"
            :step="1"
        />
      </g-field>
      <g-field
          :level="2"
          label="分割数量"
      >
        <g-input-number
            v-model="config.seriesData.axisTick.splitNumber"
            :min="0"
            :max="100"
            :step="1"
        />
      </g-field>
      <g-field
          :level="2"
          label="分割线宽度"
      >
        <g-input-number
            v-model="config.seriesData.axisTick.lineStyle.width"
            :min="0"
            :max="100"
            :step="1"
        />
      </g-field>
      <g-field
          :level="2"
          label="分割线颜色"
      >
        <g-color-picker
            v-model="config.seriesData.axisTick.lineStyle.color"
        />
      </g-field>
    </g-field-collapse>
    <g-field-collapse
        v-model="config.seriesData.splitLine.show"
        :toggle="true"
        label="分隔线"
    >
      <g-field
          :level="2"
          label="分隔线与轴线的距离"
      >
        <g-input-number
            v-model="config.seriesData.splitLine.distance"
            :min="-100"
            :max="100"
            :step="1"
        />
      </g-field>
      <g-field
          :level="2"
          label="分隔线长度"
      >
        <g-input-number
            v-model="config.seriesData.splitLine.length"
            :min="-100"
            :max="100"
            :step="1"
        />
      </g-field>
      <g-field
          :level="2"
          label="分隔线宽度"
      >
        <g-input-number
            v-model="config.seriesData.splitLine.lineStyle.width"
            :min="0"
            :max="100"
            :step="1"
        />
      </g-field>
      <g-field
          :level="2"
          label="分隔线颜色"
      >
        <g-color-picker
            v-model="config.seriesData.splitLine.lineStyle.color"
        />
      </g-field>
    </g-field-collapse>
    <g-field-collapse
        v-model="config.seriesData.axisLabel.show"
        :toggle="true"
        label="刻度标签"
    >
      <g-field
          :level="2"
          label="刻度标签距离"
      >
        <g-input-number
            v-model="config.seriesData.axisLabel.distance"
            :min="-100"
            :max="100"
            :step="1"
        />
      </g-field>
      <g-field
          :level="2"
          label="刻度标签文字颜色"
      >
        <g-color-picker
            v-model="config.seriesData.axisLabel.color"
        />
      </g-field>
      <g-field
          :level="2"
          label="刻度标签文字大小"
      >
        <g-input-number
            v-model="config.seriesData.axisLabel.fontSize"
            :min="-100"
            :max="100"
            :step="1"
        />
      </g-field>
    </g-field-collapse>
    <g-field-collapse
        v-model="config.seriesData.detail.show"
        :toggle="true"
        label="仪表盘详情                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  "
    >
      <g-field
          :level="2"
          label="宽度"
      >
        <g-input-number
            v-model="config.seriesData.detail.width"
            :min="0"
            :max="100"
            :step="1"
        />
      </g-field>
      <g-field
          :level="2"
          label="行高"
      >
        <g-input-number
            v-model="config.seriesData.detail.lineHeight"
            :min="0"
            :max="100"
            :step="1"
        />
      </g-field>
      <g-field
          :level="2"
          label="文字大小"
      >
        <g-input-number
            v-model="config.seriesData.detail.fontSize"
            :min="0"
            :max="100"
            :step="1"
        />
      </g-field>
      <g-field
          :level="2"
          label="文字颜色"
      >
        <g-color-picker
            v-model="config.seriesData.detail.color"
        />
      </g-field>
    </g-field-collapse>
    <g-field-collapse
        v-model="config.seriesData.pointer.show"
        :toggle="true"
        label="指针"
    >
      <g-field
          :level="2"
          label="位置"
      >
        <g-input-number
            v-model="config.seriesData.pointer.offsetCenter[0]"
            :min="-100"
            :max="100"
            :step="1"
        />
        <g-input-number
            v-model="config.seriesData.pointer.offsetCenter[1]"
            :min="-100"
            :max="100"
            :step="1"
        />
      </g-field>
      <g-field
          :level="2"
          label="长度"
      >
        <g-input-number
            v-model="config.seriesData.pointer.length"
            :min="1"
            :max="100"
            :step="1"
        />
      </g-field>
      <g-field
          :level="2"
          label="宽度"
      >
        <g-input-number
            v-model="config.seriesData.pointer.width"
            :min="1"
            :max="100"
            :step="1"
        />
      </g-field>
      <g-field
          :level="2"
          label="颜色"
      >
        <g-color-picker
            v-model="config.seriesData.pointer.itemStyle.color"
        />
      </g-field>
    </g-field-collapse>
  </div>
</template>
<script lang='ts'>
import { defineComponent, PropType, toRef } from 'vue'
import { fillTypes } from '@/data/select-options'
import { Gauge } from './gauge'
export default defineComponent({
  name: 'VGaugeProp',
  props: {
    com: {
      type: Object as PropType<Gauge>,
      required: true,
    },
  },
  setup(props) {
    const config = toRef(props.com, 'config')
    return {
      fillTypes,
      config,
    }
  },
})

</script>