name: Develop CI

on:
  push:
    branches:
      - dev
    paths-ignore:
      - '**.md'
      - 'demo/**'

jobs:
  develop-ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Step pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: latest

      - name: Step Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm run bootstrap

      - name: Lint
        run: pnpm run lint

      - name: Build
        run: pnpm run build
